# -*- coding: utf-8 -*-
"""ai inference-paging kv cache

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10mo0tFX47731Pof0ue7cDWO47yoaWEwC
"""

!pip install -q triton
import torch, triton, triton.language as tl
print(torch.cuda.get_device_name(0), "| triton", triton.__version__)

"""- rented GPU from google, installed Triton, lang for writing GPU worker instructions"""

import torch, triton, triton.language as tl

@triton.jit
def naive_matmul_kernel(
    a_ptr, b_ptr, c_ptr,
    M, N, K,
    stride_am, stride_ak,
    stride_bk, stride_bn,
    stride_cm, stride_cn,
    BLOCK_M: tl.constexpr, BLOCK_N: tl.constexpr, BLOCK_K: tl.constexpr,
):
    pid_m = tl.program_id(0)
    pid_n = tl.program_id(1)

    offs_m = tl.arange(0, BLOCK_M)
    offs_n = tl.arange(0, BLOCK_N)
    offs_k = tl.arange(0, BLOCK_K)

    accumulator = tl.zeros((BLOCK_M, BLOCK_N), dtype=tl.float32)

    for k_iter in range(0, tl.cdiv(K, BLOCK_K)):
        a_offs = (pid_m * BLOCK_M + offs_m[:, None]) * stride_am + \
                 (k_iter * BLOCK_K + offs_k[None, :]) * stride_ak
        b_offs = (k_iter * BLOCK_K + offs_k[:, None]) * stride_bk + \
                 (pid_n * BLOCK_N + offs_n[None, :]) * stride_bn

        a_ptrs = a_ptr + a_offs
        b_ptrs = b_ptr + b_offs

        mask_a = (pid_m * BLOCK_M + offs_m[:, None] < M) & \
                 (k_iter * BLOCK_K + offs_k[None, :] < K)
        mask_b = (k_iter * BLOCK_K + offs_k[:, None] < K) & \
                 (pid_n * BLOCK_N + offs_n[None, :] < N)

        a_block = tl.load(a_ptrs, mask=mask_a, other=0.0)
        b_block = tl.load(b_ptrs, mask=mask_b, other=0.0)

        accumulator += tl.dot(a_block, b_block)

    c_offs = (pid_m * BLOCK_M + offs_m[:, None]) * stride_cm + \
             (pid_n * BLOCK_N + offs_n[None, :]) * stride_cn
    c_ptrs = c_ptr + c_offs

    mask_c = (pid_m * BLOCK_M + offs_m[:, None] < M) & \
             (pid_n * BLOCK_N + offs_n[None, :] < N)

    tl.store(c_ptrs, accumulator, mask=mask_c)

def matmul(a, b):
    M, K = a.shape
    K2, N = b.shape
    assert K == K2
    c = torch.empty((M, N), device='cuda', dtype=torch.float32)

    BLOCK_M, BLOCK_N, BLOCK_K = 64, 64, 32
    grid = (triton.cdiv(M, BLOCK_M), triton.cdiv(N, BLOCK_N))  # how many tiles

    naive_matmul_kernel[grid](
        a, b, c,
        M, N, K,
        a.stride(0), a.stride(1),
        b.stride(0), b.stride(1),
        c.stride(0), c.stride(1),
        BLOCK_M=BLOCK_M, BLOCK_N=BLOCK_N, BLOCK_K=BLOCK_K,
    )
    return c

# Verify correctness
torch.manual_seed(0)
a = torch.randn(1024, 1024, device='cuda', dtype=torch.float16)
b = torch.randn(1024, 1024, device='cuda', dtype=torch.float16)

c_triton = matmul(a, b)
c_torch = (a @ b).float()

print("max abs error:", (c_triton - c_torch).abs().max().item())
print("match:", torch.allclose(c_triton, c_torch, atol=1e-1, rtol=1e-2))

"""- the kernel: wrote the instruction sheet for one worker"""

ms_triton = triton.testing.do_bench(lambda: matmul(a, b))
ms_torch = triton.testing.do_bench(lambda: a @ b)
flops = 2 * 1024**3
print(f"triton: {ms_triton:.3f} ms → {flops/ms_triton*1e-9:.1f} TFLOPS")
print(f"torch:  {ms_torch:.3f} ms → {flops/ms_torch*1e-9:.1f} TFLOPS")

"""the launcher- this made actual matrices A and B and pointed that we needed 256 workeds- we then verified thru PyTorch to compute the same A X B using NVIDIA and we compared the answers"""

import itertools, pandas as pd

results = []
for BM, BN, BK in itertools.product([32, 64, 128], [32, 64, 128], [32, 64]):
    try:
        def run():
            grid = (triton.cdiv(1024, BM), triton.cdiv(1024, BN))
            naive_matmul_kernel[grid](
                a, b, c_out,
                1024, 1024, 1024,
                a.stride(0), a.stride(1),
                b.stride(0), b.stride(1),
                c_out.stride(0), c_out.stride(1),
                BLOCK_M=BM, BLOCK_N=BN, BLOCK_K=BK,
            )
        c_out = torch.empty((1024, 1024), device='cuda', dtype=torch.float32)
        ms = triton.testing.do_bench(run)
        tflops = 2 * 1024**3 / ms * 1e-9
        results.append((BM, BN, BK, round(ms, 3), round(tflops, 1)))
    except Exception as e:
        results.append((BM, BN, BK, None, None))

df = pd.DataFrame(results, columns=["BM", "BN", "BK", "ms", "TFLOPS"])
print(df.sort_values("TFLOPS", ascending=False).to_string(index=False))

import itertools, pandas as pd

results = []
c_out = torch.empty((1024, 1024), device='cuda', dtype=torch.float32)
for num_warps, num_stages in itertools.product([2, 4, 8], [1, 2, 3, 4, 5]):
    try:
        def run():
            grid = (triton.cdiv(1024, 32), triton.cdiv(1024, 64))
            naive_matmul_kernel[grid](
                a, b, c_out,
                1024, 1024, 1024,
                a.stride(0), a.stride(1),
                b.stride(0), b.stride(1),
                c_out.stride(0), c_out.stride(1),
                BLOCK_M=32, BLOCK_N=64, BLOCK_K=32,
                num_warps=num_warps, num_stages=num_stages,
            )
        ms = triton.testing.do_bench(run)
        results.append((num_warps, num_stages, round(ms, 3), round(2*1024**3/ms*1e-9, 1)))
    except Exception:
        results.append((num_warps, num_stages, None, None))

df2 = pd.DataFrame(results, columns=["warps", "stages", "ms", "TFLOPS"])
print(df2.sort_values("TFLOPS", ascending=False).to_string(index=False))

import torch, math

def naive_attention(q, k, v):
    # q, k, v: (N, d) fp16
    d = q.shape[-1]
    s = (q @ k.T).float() / math.sqrt(d)      # (N, N)  ← the villain, materialized
    s = s - s.max(dim=-1, keepdim=True).values  # stability trick
    p = torch.exp(s)
    p = p / p.sum(dim=-1, keepdim=True)
    return (p.to(v.dtype) @ v)                # (N, d)

# correctness vs PyTorch's built-in
N, d = 1024, 64
q, k, v = (torch.randn(N, d, device='cuda', dtype=torch.float16) for _ in range(3))
out = naive_attention(q, k, v)
ref = torch.nn.functional.scaled_dot_product_attention(
    q[None, None], k[None, None], v[None, None]
)[0, 0]
print("max abs error:", (out - ref).abs().max().item())