# -*- coding: utf-8 -*-
"""ai inference-paging kv cache

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10mo0tFX47731Pof0ue7cDWO47yoaWEwC
"""

!pip install -q triton
import torch, triton, triton.language as tl
print(torch.cuda.get_device_name(0), "| triton", triton.__version__)

"""- rented GPU from google, installed Triton, lang for writing GPU worker instructions"""

import torch, triton, triton.language as tl

@triton.jit
def naive_matmul_kernel(
    a_ptr, b_ptr, c_ptr,
    M, N, K,
    stride_am, stride_ak,
    stride_bk, stride_bn,
    stride_cm, stride_cn,
    BLOCK_M: tl.constexpr, BLOCK_N: tl.constexpr, BLOCK_K: tl.constexpr,
):
    pid_m = tl.program_id(0)
    pid_n = tl.program_id(1)

    offs_m = tl.arange(0, BLOCK_M)
    offs_n = tl.arange(0, BLOCK_N)
    offs_k = tl.arange(0, BLOCK_K)

    accumulator = tl.zeros((BLOCK_M, BLOCK_N), dtype=tl.float32)

    for k_iter in range(0, tl.cdiv(K, BLOCK_K)):
        a_offs = (pid_m * BLOCK_M + offs_m[:, None]) * stride_am + \
                 (k_iter * BLOCK_K + offs_k[None, :]) * stride_ak
        b_offs = (k_iter * BLOCK_K + offs_k[:, None]) * stride_bk + \
                 (pid_n * BLOCK_N + offs_n[None, :]) * stride_bn

        a_ptrs = a_ptr + a_offs
        b_ptrs = b_ptr + b_offs

        mask_a = (pid_m * BLOCK_M + offs_m[:, None] < M) & \
                 (k_iter * BLOCK_K + offs_k[None, :] < K)
        mask_b = (k_iter * BLOCK_K + offs_k[:, None] < K) & \
                 (pid_n * BLOCK_N + offs_n[None, :] < N)

        a_block = tl.load(a_ptrs, mask=mask_a, other=0.0)
        b_block = tl.load(b_ptrs, mask=mask_b, other=0.0)

        accumulator += tl.dot(a_block, b_block)

    c_offs = (pid_m * BLOCK_M + offs_m[:, None]) * stride_cm + \
             (pid_n * BLOCK_N + offs_n[None, :]) * stride_cn
    c_ptrs = c_ptr + c_offs

    mask_c = (pid_m * BLOCK_M + offs_m[:, None] < M) & \
             (pid_n * BLOCK_N + offs_n[None, :] < N)

    tl.store(c_ptrs, accumulator, mask=mask_c)

def matmul(a, b):
    M, K = a.shape
    K2, N = b.shape
    assert K == K2
    c = torch.empty((M, N), device='cuda', dtype=torch.float32)

    BLOCK_M, BLOCK_N, BLOCK_K = 64, 64, 32
    grid = (triton.cdiv(M, BLOCK_M), triton.cdiv(N, BLOCK_N))  # how many tiles

    naive_matmul_kernel[grid](
        a, b, c,
        M, N, K,
        a.stride(0), a.stride(1),
        b.stride(0), b.stride(1),
        c.stride(0), c.stride(1),
        BLOCK_M=BLOCK_M, BLOCK_N=BLOCK_N, BLOCK_K=BLOCK_K,
    )
    return c

# Verify correctness
torch.manual_seed(0)
a = torch.randn(1024, 1024, device='cuda', dtype=torch.float16)
b = torch.randn(1024, 1024, device='cuda', dtype=torch.float16)

c_triton = matmul(a, b)
c_torch = (a @ b).float()

print("max abs error:", (c_triton - c_torch).abs().max().item())
print("match:", torch.allclose(c_triton, c_torch, atol=1e-1, rtol=1e-2))

"""- the kernel: wrote the instruction sheet for one worker"""

ms_triton = triton.testing.do_bench(lambda: matmul(a, b))
ms_torch = triton.testing.do_bench(lambda: a @ b)
flops = 2 * 1024**3
print(f"triton: {ms_triton:.3f} ms → {flops/ms_triton*1e-9:.1f} TFLOPS")
print(f"torch:  {ms_torch:.3f} ms → {flops/ms_torch*1e-9:.1f} TFLOPS")

"""the launcher- this made actual matrices A and B and pointed that we needed 256 workeds- we then verified thru PyTorch to compute the same A X B using NVIDIA and we compared the answers"""

import itertools, pandas as pd

results = []
for BM, BN, BK in itertools.product([32, 64, 128], [32, 64, 128], [32, 64]):
    try:
        def run():
            grid = (triton.cdiv(1024, BM), triton.cdiv(1024, BN))
            naive_matmul_kernel[grid](
                a, b, c_out,
                1024, 1024, 1024,
                a.stride(0), a.stride(1),
                b.stride(0), b.stride(1),
                c_out.stride(0), c_out.stride(1),
                BLOCK_M=BM, BLOCK_N=BN, BLOCK_K=BK,
            )
        c_out = torch.empty((1024, 1024), device='cuda', dtype=torch.float32)
        ms = triton.testing.do_bench(run)
        tflops = 2 * 1024**3 / ms * 1e-9
        results.append((BM, BN, BK, round(ms, 3), round(tflops, 1)))
    except Exception as e:
        results.append((BM, BN, BK, None, None))

df = pd.DataFrame(results, columns=["BM", "BN", "BK", "ms", "TFLOPS"])
print(df.sort_values("TFLOPS", ascending=False).to_string(index=False))

import itertools, pandas as pd

results = []
c_out = torch.empty((1024, 1024), device='cuda', dtype=torch.float32)
for num_warps, num_stages in itertools.product([2, 4, 8], [1, 2, 3, 4, 5]):
    try:
        def run():
            grid = (triton.cdiv(1024, 32), triton.cdiv(1024, 64))
            naive_matmul_kernel[grid](
                a, b, c_out,
                1024, 1024, 1024,
                a.stride(0), a.stride(1),
                b.stride(0), b.stride(1),
                c_out.stride(0), c_out.stride(1),
                BLOCK_M=32, BLOCK_N=64, BLOCK_K=32,
                num_warps=num_warps, num_stages=num_stages,
            )
        ms = triton.testing.do_bench(run)
        results.append((num_warps, num_stages, round(ms, 3), round(2*1024**3/ms*1e-9, 1)))
    except Exception:
        results.append((num_warps, num_stages, None, None))

df2 = pd.DataFrame(results, columns=["warps", "stages", "ms", "TFLOPS"])
print(df2.sort_values("TFLOPS", ascending=False).to_string(index=False))

import itertools

import pandas as pd
import torch
import triton

M = N = K = 1024
NUM_SMS = torch.cuda.get_device_properties(0).multi_processor_count

# Assumes `a`, `b` already exist from an earlier cell. If not, uncomment:
# a = torch.randn((M, K), device="cuda", dtype=torch.float32)
# b = torch.randn((K, N), device="cuda", dtype=torch.float32)

c_out = torch.empty((M, N), device="cuda", dtype=torch.float32)
ref = a @ b

results = []

for BM, BN, BK in itertools.product([32, 64, 128], [32, 64, 128], [32, 64]):
    grid = (triton.cdiv(M, BM), triton.cdiv(N, BN))
    n_programs = grid[0] * grid[1]

    def run():
        naive_matmul_kernel[grid](
            a, b, c_out,
            M, N, K,
            a.stride(0), a.stride(1),
            b.stride(0), b.stride(1),
            c_out.stride(0), c_out.stride(1),
            BLOCK_M=BM, BLOCK_N=BN, BLOCK_K=BK,
        )

    try:
        compiled = naive_matmul_kernel[grid](
            a, b, c_out,
            M, N, K,
            a.stride(0), a.stride(1),
            b.stride(0), b.stride(1),
            c_out.stride(0), c_out.stride(1),
            BLOCK_M=BM, BLOCK_N=BN, BLOCK_K=BK,
        )

        n_regs = getattr(compiled, "n_regs", None)
        n_spills = getattr(compiled, "n_spills", None)

        torch.cuda.synchronize()
        correct = torch.allclose(c_out, ref, atol=1e-2, rtol=1e-2)

        ms = triton.testing.do_bench(run)
        tflops = 2 * M * N * K / ms * 1e-9

        results.append(
            (BM, BN, BK, n_programs, n_programs / NUM_SMS,
             n_regs, n_spills, round(ms, 3), round(tflops, 2), correct)
        )

    except Exception as e:
        print(f"BM={BM} BN={BN} BK={BK} -> failed: {e}")
        results.append((BM, BN, BK, n_programs, n_programs / NUM_SMS,
                        None, None, None, None, None))

df = pd.DataFrame(
    results,
    columns=["BM", "BN", "BK", "programs", "prog/SM",
             "n_regs", "n_spills", "ms", "TFLOPS", "correct"],
)

print(f"Device has {NUM_SMS} SMs\n")
print(df.sort_values("TFLOPS", ascending=False).to_string(index=False))

import itertools

import pandas as pd
import torch
import triton
import triton.language as tl


# NOTE: this redefines naive_matmul_kernel — it will overwrite the symbol
# from your earlier cell for the rest of the session. Rename it if you
# want to keep both versions around side by side.
@triton.jit
def naive_matmul_kernel(
    a_ptr, b_ptr, c_ptr,
    M, N, K,
    stride_am, stride_ak,
    stride_bk, stride_bn,
    stride_cm, stride_cn,
    BLOCK_M: tl.constexpr, BLOCK_N: tl.constexpr, BLOCK_K: tl.constexpr,
):
    pid_m = tl.program_id(0)
    pid_n = tl.program_id(1)

    offs_m = tl.arange(0, BLOCK_M)
    offs_n = tl.arange(0, BLOCK_N)
    offs_k = tl.arange(0, BLOCK_K)

    accumulator = tl.zeros((BLOCK_M, BLOCK_N), dtype=tl.float32)

    for k_iter in range(0, tl.cdiv(K, BLOCK_K)):
        a_offs = (pid_m * BLOCK_M + offs_m[:, None]) * stride_am + \
                 (k_iter * BLOCK_K + offs_k[None, :]) * stride_ak
        b_offs = (k_iter * BLOCK_K + offs_k[:, None]) * stride_bk + \
                 (pid_n * BLOCK_N + offs_n[None, :]) * stride_bn

        a_ptrs = a_ptr + a_offs
        b_ptrs = b_ptr + b_offs

        mask_a = (pid_m * BLOCK_M + offs_m[:, None] < M) & \
                 (k_iter * BLOCK_K + offs_k[None, :] < K)
        mask_b = (k_iter * BLOCK_K + offs_k[:, None] < K) & \
                 (pid_n * BLOCK_N + offs_n[None, :] < N)

        a_block = tl.load(a_ptrs, mask=mask_a, other=0.0)
        b_block = tl.load(b_ptrs, mask=mask_b, other=0.0)

        accumulator += tl.dot(a_block, b_block)

    c_offs = (pid_m * BLOCK_M + offs_m[:, None]) * stride_cm + \
             (pid_n * BLOCK_N + offs_n[None, :]) * stride_cn
    c_ptrs = c_ptr + c_offs

    mask_c = (pid_m * BLOCK_M + offs_m[:, None] < M) & \
             (pid_n * BLOCK_N + offs_n[None, :] < N)

    # cast fp32 accumulator down to whatever c_ptr's dtype actually is
    tl.store(c_ptrs, accumulator.to(c_ptr.dtype.element_ty), mask=mask_c)


# --- one-time correctness check on the reworked kernel ---
c_check = torch.empty((1024, 1024), device='cuda', dtype=a.dtype)  # fp16, matches a
grid = (triton.cdiv(1024, 64), triton.cdiv(1024, 64))

naive_matmul_kernel[grid](
    a, b, c_check, 1024, 1024, 1024,
    a.stride(0), a.stride(1), b.stride(0), b.stride(1),
    c_check.stride(0), c_check.stride(1),
    BLOCK_M=64, BLOCK_N=64, BLOCK_K=32,
)

c_ref = (a.float() @ b.float()).to(a.dtype)  # compute in fp32, cast back to fp16
max_err = (c_check - c_ref).abs().max().item()

print("max abs error:", max_err)
print("match:", torch.allclose(c_check, c_ref, atol=5e-1, rtol=5e-2))  # loosened for fp16


# --- register/spill sweep across all 18 tile configs ---
results = []
c_out = torch.empty((1024, 1024), device='cuda', dtype=a.dtype)  # fp16, matches a

for BM, BN, BK in itertools.product([32, 64, 128], [32, 64, 128], [32, 64]):
    grid = (triton.cdiv(1024, BM), triton.cdiv(1024, BN))

    def run():
        naive_matmul_kernel[grid](
            a, b, c_out, 1024, 1024, 1024,
            a.stride(0), a.stride(1), b.stride(0), b.stride(1),
            c_out.stride(0), c_out.stride(1),
            BLOCK_M=BM, BLOCK_N=BN, BLOCK_K=BK,
        )

    try:
        compiled = naive_matmul_kernel[grid](
            a, b, c_out, 1024, 1024, 1024,
            a.stride(0), a.stride(1), b.stride(0), b.stride(1),
            c_out.stride(0), c_out.stride(1),
            BLOCK_M=BM, BLOCK_N=BN, BLOCK_K=BK,
        )
        n_regs, n_spills = compiled.n_regs, compiled.n_spills
        ms = triton.testing.do_bench(run)
        tflops = 2 * 1024**3 / ms * 1e-9
    except Exception as e:
        n_regs = n_spills = ms = tflops = None
        print(f"BM={BM} BN={BN} BK={BK} -> failed: {e}")

    results.append((BM, BN, BK, n_regs, n_spills,
                    round(ms, 3) if ms else None,
                    round(tflops, 1) if tflops else None))

df_regs = pd.DataFrame(
    results,
    columns=["BM", "BN", "BK", "n_regs", "n_spills", "ms", "TFLOPS"],
)
print(df_regs.sort_values("TFLOPS", ascending=False).to_string(index=False))

import pandas as pd
import torch
import triton

M = N = K = 1024
c_out = torch.empty((M, N), device="cuda", dtype=a.dtype)

# 64x64x64 -> predicted 64 (fallback 85), spills should DROP from 476
# 128x128x32 -> predicted exactly 64 (the zero-parameter floor check)
configs = [(64, 64, 64), (128, 128, 32)]

rows = []

for BM, BN, BK in configs:
    for nw in [4, 8]:
        grid = (triton.cdiv(M, BM), triton.cdiv(N, BN))

        def run(nw=nw, BM=BM, BN=BN, BK=BK):
            naive_matmul_kernel[grid](
                a, b, c_out, M, N, K,
                a.stride(0), a.stride(1), b.stride(0), b.stride(1),
                c_out.stride(0), c_out.stride(1),
                BLOCK_M=BM, BLOCK_N=BN, BLOCK_K=BK,
                num_warps=nw,
            )

        try:
            compiled = naive_matmul_kernel[grid](
                a, b, c_out, M, N, K,
                a.stride(0), a.stride(1), b.stride(0), b.stride(1),
                c_out.stride(0), c_out.stride(1),
                BLOCK_M=BM, BLOCK_N=BN, BLOCK_K=BK,
                num_warps=nw,
            )
            ms = triton.testing.do_bench(run)
            rows.append((BM, BN, BK, nw, nw * 32,
                         compiled.n_regs, compiled.n_spills,
                         round(ms, 3), round(2 * M * N * K / ms * 1e-9, 2)))
        except Exception as e:
            print(f"{BM}x{BN}x{BK} num_warps={nw} -> failed: {e}")

df = pd.DataFrame(
    rows,
    columns=["BM", "BN", "BK", "num_warps", "threads",
             "n_regs", "n_spills", "ms", "TFLOPS"],
)
print(df.to_string(index=False))
print("\nPredicted menu at num_warps=8: {255, 128, 85, 64}")